// SPEC-FIGMA-008 REQ-04 — cloudflared TunnelAdapter.
// Production adapter that spawns the `cloudflared tunnel --url …` binary and
// parses the assigned `*.trycloudflare.com` URL from stderr/stdout.
//
// Tests inject mock adapters; this module is the only place that touches a
// real subprocess. Bearer is generated by the manager, not by cloudflared.
//
// @AX:WARN:[AUTO] — Default-safe (NFR-01) requires that this adapter is not
// constructed unless the user passed `--tunnel=cloudflared`. The manager
// guards opt-in confirmation; this adapter trusts the manager's gate.

import { spawn, type ChildProcess } from "node:child_process";

import type { TunnelAdapter, TunnelAttachResult } from "./tunnel-adapter.js";

export interface CloudflaredAdapterOptions {
  readonly binaryPath?: string;
  readonly localPort: number;
  readonly spawnTimeoutMs?: number;
}

const TRYCLOUDFLARE_URL_RE = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/;
const DEFAULT_SPAWN_TIMEOUT_MS = 15_000;

export class CloudflaredTunnelAdapter implements TunnelAdapter {
  private proc: ChildProcess | null = null;
  private readonly binaryPath: string;
  private readonly localPort: number;
  private readonly spawnTimeoutMs: number;

  constructor(opts: CloudflaredAdapterOptions) {
    this.binaryPath = opts.binaryPath ?? "cloudflared";
    this.localPort = opts.localPort;
    this.spawnTimeoutMs = opts.spawnTimeoutMs ?? DEFAULT_SPAWN_TIMEOUT_MS;
  }

  async attach(): Promise<TunnelAttachResult> {
    if (this.proc) {
      throw new Error("cloudflared adapter: already attached");
    }
    const args = [
      "tunnel",
      "--no-autoupdate",
      "--url",
      `http://127.0.0.1:${this.localPort}`,
    ];
    const proc = spawn(this.binaryPath, args, {
      stdio: ["ignore", "pipe", "pipe"],
    });
    this.proc = proc;

    const url = await readUrlFromOutput(proc, this.spawnTimeoutMs);
    return { tunnelUrl: url };
  }

  async detach(): Promise<void> {
    if (!this.proc) return;
    try {
      this.proc.kill("SIGTERM");
    } catch {
      /* best effort */
    }
    this.proc = null;
  }
}

function readUrlFromOutput(proc: ChildProcess, timeoutMs: number): Promise<string> {
  return new Promise((resolve, reject) => {
    let settled = false;
    const onChunk = (chunk: Buffer): void => {
      if (settled) return;
      const text = chunk.toString("utf8");
      const match = text.match(TRYCLOUDFLARE_URL_RE);
      if (match) {
        settled = true;
        clearTimeout(timer);
        resolve(match[0]);
      }
    };
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      try { proc.kill("SIGTERM"); } catch { /* ignore */ }
      reject(new Error("cloudflared tunnel URL not received within timeout"));
    }, timeoutMs);

    proc.stdout?.on("data", onChunk);
    proc.stderr?.on("data", onChunk);
    proc.on("error", (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(err);
    });
    proc.on("exit", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(new Error(`cloudflared exited before URL ready (code=${code ?? "?"})`));
    });
  });
}
